import { User, Video, Comment } from './types';

// This data is a copy from the frontend's mockApi to simulate a backend database.

export const mockUsers: User[] = [
  {
    id: 'u1',
    username: 'react_dev',
    email: 'dev@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=u1',
    role: 'admin',
    status: 'active',
    isVerified: true,
    joinDate: '2023-01-15',
    lastLogin: '2024-07-20',
    bio: 'Building cool stuff with React & TypeScript. Follow for more! 🚀',
    followers: 12500,
    following: 321,
    totalLikes: 8900,
    followingIds: ['u2'],
    likedVideoIds: ['v2', 'v5'],
    wallet: {
      balance: 1250,
      transactions: [
        { id: 't1', type: 'purchase', amount: 500, description: 'Purchased Fan Pack', timestamp: '2024-07-19' },
        { id: 't2', type: 'gift_sent', amount: 100, description: 'Sent a Rose gift', timestamp: '2024-07-18' },
        { id: 't3', type: 'reward', amount: 50, description: 'Daily Login Reward', timestamp: '2024-07-18' },
      ],
    },
    creatorStats: { totalEarnings: 5430.50, receivedGiftsCount: 890 },
    level: 25,
    xp: 150,
    streakCount: 12,
    badges: [
      { id: 'b1', name: 'Early Bird', icon: '🐦', description: 'Joined in the first year.' },
      { id: 'b2', name: 'Top Gifter', icon: '🎁', description: 'Sent over 100 gifts.' },
    ],
  },
  {
    id: 'u2',
    username: 'creative_cat',
    email: 'cat@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=u2',
    role: 'creator',
    status: 'active',
    isVerified: true,
    joinDate: '2023-03-22',
    lastLogin: '2024-07-21',
    bio: 'Just a cat who loves to create art and dance. 🎨',
    followers: 250001,
    following: 150,
    totalLikes: 12000,
    followingIds: [],
    likedVideoIds: ['v3', 'v6'],
    level: 30,
    xp: 180,
    streakCount: 5,
  },
  {
    id: 'u3',
    username: 'gamer_god',
    email: 'gamer@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=u3',
    role: 'creator',
    status: 'suspended',
    isVerified: false,
    joinDate: '2023-08-10',
    lastLogin: '2024-07-15',
    bio: 'Pro gamer. Streaming daily.',
    followers: 1200000,
    following: 5,
    totalLikes: 55000,
    followingIds: [],
    likedVideoIds: ['v1'],
    level: 50,
    xp: 900,
  },
    {
    id: 'u4',
    username: 'foodie_queen',
    email: 'food@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=u4',
    role: 'user',
    status: 'active',
    isVerified: true,
    joinDate: '2024-01-05',
    lastLogin: '2024-07-21',
    bio: 'Exploring the best food spots!',
    followers: 5200,
    following: 800,
    totalLikes: 1700,
    followingIds: ['u1', 'u2', 'u3'],
    likedVideoIds: ['v1', 'v2', 'v3', 'v5', 'v6'],
    level: 15,
  },
  {
    id: 'u5',
    username: 'travel_bug',
    email: 'travel@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=u5',
    role: 'user',
    status: 'banned',
    isVerified: false,
    joinDate: '2024-02-14',
    lastLogin: '2024-06-01',
    bio: 'Wanderlust.',
    followers: 10,
    following: 50,
    totalLikes: 20,
    followingIds: [],
    likedVideoIds: [],
    level: 2,
  },
];

export const mockVideos: Video[] = [
  {
    id: 'v1',
    videoSources: [{ quality: 'Auto', url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4' }],
    description: 'This is a fun video of a bunny!',
    user: mockUsers[1],
    likes: 12000,
    comments: 2,
    shares: 123,
    views: 250000,
    commentsData: [
      { id: 'c1', user: mockUsers[2], text: 'Great video!', timestamp: '2h ago' },
      { id: 'c2', user: mockUsers[3], text: 'So cute!', timestamp: '1h ago' },
    ],
    thumbnailUrl: 'https://i.ytimg.com/vi/aqz-KE-bpKQ/maxresdefault.jpg',
    status: 'approved',
    uploadDate: '2024-07-10',
  },
  {
    id: 'v2',
    videoSources: [{ quality: 'Auto', url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4' }],
    description: 'Check out this cool animation. #animation',
    user: mockUsers[2],
    likes: 55000,
    comments: 0,
    shares: 800,
    views: 1200000,
    commentsData: [],
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Elephants_Dream_s5_proog.jpg/1200px-Elephants_Dream_s5_proog.jpg',
    status: 'approved',
    uploadDate: '2024-07-09',
  },
  {
    id: 'v3',
    videoSources: [{ quality: 'Auto', url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4' }],
    description: 'Coding my new project!',
    user: mockUsers[0],
    likes: 8900,
    comments: 0,
    shares: 300,
    views: 50000,
    commentsData: [],
    thumbnailUrl: 'https://i.ytimg.com/vi/Dr91pn3xcbU/maxresdefault.jpg',
    status: 'pending',
    uploadDate: '2024-07-21',
  },
  {
    id: 'v4',
    videoSources: [{ quality: 'Auto', url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4' }],
    description: 'Travel vlog from Bali!',
    user: mockUsers[4],
    likes: 20,
    comments: 0,
    shares: 1,
    views: 380,
    commentsData: [],
    thumbnailUrl: 'https://i.ytimg.com/vi/E1_h_ JegGoE/maxresdefault.jpg',
    status: 'removed',
    uploadDate: '2024-05-15',
  },
];